POST http://localhost:3001/api/stone
Content-Type: application/json 
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpkZm90byIsImlkIjoiNWYzNjY1ZjM1NjMwYTI0ZTkwMmVkYWYxIiwiaWF0IjoxNjAyNzg3NTI3fQ.hihnkm4RheVxV0VgiqnOFRTcwAkh7j0YLwv0hko9o0A

{
    "name": "Infinito",
    "type": "Marbre",
    "color": "Blanc",
    "origin": "Macédoine",
    "finish": "Poli",
    "thickness": "3cm, 2cm",
    "image": "assets/img/stone/Infinito1.jpg",
    "detail": [
        {"image": "assets/img/stone/Infinito2.jpg"},
        {"image": "assets/img/stone/Infinito3.jpg"},
        {"image": "assets/img/stone/Infinito4.jpg"},
        {"image": "assets/img/stone/Infinito5.jpg"},
        {"image": "assets/img/stone/Infinito6.jpg"},
        {"image": "assets/img/stone/Infinito7.jpg"},
        {"image": "assets/img/stone/Infinito8.jpg"}
    ]
}