POST http://localhost:3001/api/stones
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MDFhNzBjNGIzYWE2OWFjNzkwZDVkNWEiLCJpYXQiOjE2MTIzNDU2ODR9.WQvPzlW9dx7qrr9Nr82F7lXltH42nISl-y76fOunBaQ

{
       "name": "Azul Novae",
       "type": "Granit",
       "color": "Beige",
       "origin": "Inde",
       "finish": "Poli",
       "thickness": "2cm, 3cm",
       "dimension": "301x183",
       "image": "assets/img/stone/granit/clairs/AzulNovae1.jpg",
       "detail": [
           {"image": "assets/img/stone/granit/clairs/AzulNovae3.jpg"},
           {"image": "assets/img/stone/granit/clairs/AzulNovae4.jpg"},
           {"image": "assets/img/stone/granit/clairs/AzulNovae5.jpg"},
           {"image": "assets/img/stone/granit/clairs/AzulNovae6.jpg"},
           {"image": "assets/img/stone/granit/clairs/AzulNovae7.jpg"},
           {"image": "assets/img/stone/granit/clairs/AzulNovae8.jpg"}
       ]
}

//admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MDFhNzBjNGIzYWE2OWFjNzkwZDVkNWEiLCJpYXQiOjE2MTIzNDU2ODR9.WQvPzlW9dx7qrr9Nr82F7lXltH42nISl-y76fOunBaQ

//test: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYwMTkwY2MwYjM1ODAzODRmM2YwMzAxZSIsImlhdCI6MTYxMjI1NDU5Mn0.aPx16l5WiXIDDtnApSi6szD8aFzzay_yE_idR-R-QxQ