PUT http://localhost:3001/api/stones/5f2282290885e88ef0f70a83
Content-Type: application/json

{
    "name": "Infinito",
    "type": "Marbre",
    "color": "Blanc",
    "origin": "Macédoine",
    "finish": "Poli",
    "thickness": "3cm, 2cm",
    "image": "assets/img/stone/Infinito1.jpg",
    "detail": [
        {"image": "assets/img/stone/Infinito2.jpg"},
        {"image": "assets/img/stone/Infinito3.jpg"},
        {"image": "assets/img/stone/Infinito4.jpg"},
        {"image": "assets/img/stone/Infinito5.jpg"},
        {"image": "assets/img/stone/Infinito6.jpg"},
        {"image": "assets/img/stone/Infinito7.jpg"},
        {"image": "assets/img/stone/Infinito8.jpg"}
    ]
}